
function setup_history() {
	ZSH_AUTOSUGGEST_STRATEGY=(history completion)

	export HISTFILE=~/.zsh_history
	export HISTSIZE=1000000000
	export HISTFILESIZE=$HISTSIZE
	export SAVEHIST=$HISTSIZE
	export HISTORY_SUBSTRING_SEARCH_PREFIXED=1
	export HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
	export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="normal"
	export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND="normal"
	alias history="history 1"

	export HIST_STAMPS="dd.mm.yyyy"
	setopt append_history
	setopt share_history
	setopt extended_history
	setopt hist_find_no_dups
	setopt hist_expire_dups_first
	setopt hist_reduce_blanks
	setopt hist_ignore_all_dups
}

function setup_readline() {
	setopt numeric_glob_sort

	export WORDCHARS="*?.[]~!#$%^<>"
	zmodload zsh/terminfo
	bindkey -M viins $terminfo[kcuu1] history-substring-search-up
	bindkey -M viins $terminfo[kcud1] history-substring-search-down
}

function setup_prompt() {
	#set colors
	export bold="%{%B%}"
	export red="${bold}%{%F{#ff8888}%}";
	export green="${bold}%{%F{#88ff88}%}";
	export blue="${bold}%{%F{#8888ff}%}";
	export cyan="${bold}%{%F{#88ffff}%}";
	export reset="${bold}%{%f%b%}";

	function update_prompt() {
		# --------------------
		# setup status
		local st=$?;

		if [ "$st" = "0" ]; then
			st="${green}➜${reset}";
		else
			st="${red}($st)$reset";
		fi

		# setup cwd
		# --------------------
		local cwd;

		cwd=${PWD##*/}
		if [ "$cwd" = "" ]; then
			cwd="/";
		elif [ "$PWD" = "$HOME" ]; then
			cwd="~";
		fi
		cwd=${cyan}${cwd}${reset};

		# --------------------
		# setup current branch
		local branch=$(/usr/bin/git branch --show-current 2>/dev/null);
		local head=$(git rev-parse --short HEAD 2>/dev/null)

		if [ -z "$branch" ]; then
			branch=$(git describe --exact-match $head 2>/dev/null)
		fi

		if [ -z "$branch" ]; then
			branch=$head
		fi

		if [ "$branch" != "" ]; then
			branch=" ${blue}git:(${red}${branch}${blue})${reset}";
		fi

		export PS1="${st} ${cwd}${branch} "
	}

	autoload -Uz add-zsh-hook
	add-zsh-hook precmd update_prompt
}

function setup_ccache() {
	export PATH=/usr/lib/ccache/:$HOME/.local/bin:/usr/local/bin:$PATH
}

function setup_aliases() {
	alias grep='grep --color=always'
	alias clr=clear
	alias ls='ls --color=auto'
	alias cd..='cd ..'
	alias cd...='cd ...'
	alias cd-='cd -'
	alias hist='history | fzf'

	alias umake='/usr/bin/make'
	alias make='make -erRS --warn-undefined-variables '
	alias m='make'
	alias mc='make clean'
	alias re="make clean && rm -rf build && make -j $(nproc)"

	alias ugit='/usr/bin/git'
	alias g='git'
	alias git='git'
	alias gaa='git add --all'
	alias gba='git branch --all'
	alias gdw='git diff --word-diff'
	alias gf='git fetch'
	alias gm='git merge'
	alias grf='git reflog'
	alias grb='git rebase'
	alias grbc='git rebase --continue'
	alias gs='git status'
	alias gss='git status --short'
	alias ga='git add'
	alias gb='git branch'
	alias gc='git commit --signoff -m'
	alias gca='git commit --amend'
	alias gco='git checkout'
	alias gcp='git cherry-pick'
	alias gcpc='git cherry-pick --continue'
	alias gd='git diff'
	alias gds='git diff --staged'
	alias gl='git log --oneline --first-parent'
	alias gla='git log --oneline --all --graph'
	alias gp='git push'
	alias gpu='git pull'
	alias gr='git reset'
	alias gw='git switch'

	alias v='nvim'
	alias nv='nvim'
}

function setup_git() {
	echo "Signed-off-by: $(git config user.name) <$(git config user.email)>" > ~/.gitmessage.txt

	git config --global commit.template ~/.gitmessage.txt
	git config --global commit.gpgsign true
	git config --global user.signingkey "488AA56EA550DE76"
	git config --global gpg.program gpg
	git config --global core.editor nvim
}

function mk() {
	make -j $(nproc) $@ 2>&1 >/dev/null | less -R
}

function vf() {
	nvim $(find . -name $@)
}

function gps() {
	find . -type f -name "*$2*" ! -name '*.swp' ! -name 'tags' -exec grep -Hn "$1" --color=always {} \;
}

function moveall() {
	for f in $(ls -a); do
		if [[ $f != '.git' ]] && [[ $f != $1 ]] && [[ $f != '.' && $f != '..' ]]; then
			echo moving $f to $1
			mv $f $1
		fi
	done
}

function top-contrib {
	since="${1:-'30 days ago'}"
	git log --since="$since" | grep 'Signed-off-by' | tr -d '<>' | sort | uniq -c | sort -bgr
}

# =============================================================================
# PLUGINS

function setup_plugins() {
	if ! [ -e ~/.antidote ]; then
		echo 'installing antidote'
		/usr/bin/git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
	fi
	source ~/.antidote/antidote.zsh
	antidote load
}

function plugin_zsh_syntax_highlightning() {
	export ZSH_THEME="robbyrussell"
	export ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=blue,bold'
	export ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=red,bold'
	export ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=yellow,bold'
	export ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=magenta,bold'
	export ZSH_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
	export ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=yellow,bold'
	export ZSH_HIGHLIGHT_STYLES[path]='bold,underline'
	export ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='bold'
	export ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='bold'
	export ZSH_HIGHLIGHT_STYLES[redirection]='fg=yellow,bold'
	export ZSH_HIGHLIGHT_STYLES[arg0]='fg=green,bold'
}

# =============================================================================
# YANDEX
function setup_yandex() {
	# The next line updates PATH for Yandex Cloud Private CLI.
	if [ -f '/home/tlucanti/ycp/path.bash.inc' ]; then source '/home/tlucanti/ycp/path.bash.inc'; fi

	# pssh autocomplete
	source ~/.pssh/complete.zsh

	cd /
	arc mount --repository cloudia ~/cloudia 2> /dev/null
	cd - > /dev/null
}


# GLOBAL SETUP
setup_history
setup_readline
#setup_prompt
setup_ccache
setup_aliases
setup_git

# LOCAL SETUP
# setup_yandex

source ~/.oh-my-zsh/oh-my-zsh.sh

setup_plugins
plugin_zsh_syntax_highlightning

